name: Publish NuGet package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure tag looks like vMAJOR.MINOR.PATCH
        run: |
          if ! [[ "${GITHUB_REF_NAME}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Tag ${GITHUB_REF_NAME} is not vMAJOR.MINOR.PATCH"; exit 1
          fi

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Kleer/Kleer.csproj

      - name: Build (Release)
        run: dotnet build Kleer/Kleer.csproj -c Release --no-restore

      - name: Pack (use tag as package version)
        run: dotnet pack Kleer/Kleer.csproj -c Release --no-build --no-restore /p:Version=${{ env.VERSION }}

      - name: Publish to NuGet
        run: dotnet nuget push Kleer/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
